spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JumperYu/bradypod
          search-paths: /**
          username: previous_yu@163.com
          password: zxm2006
      label: master
      uri: http://localhost:8080/
  profile:
          dev

server:
  port: 8090

#eureka:
#  client:
#    serviceUrl:
#       defaultZone: http://localhost:1111/eureka/
#    fetch-registry: false
#    register-with-eureka: false