spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JumperYu/bradypod
          search-paths: bradypod.springcloud/config-repo
#          username: ***
#          password: ***
      label: master

server:
  port: 8888