package bradypod.framework.vm.anq;

/**
 * 老生常谈  \ u表示这是一个unicode字符后面紧跟16进制
 * 
* Generated by the IBM IDL-to-Java compiler, version 1.0
* from F:\TestRoot\apps\a1\ units\include\PolicyHome.idl   --- Here
* Wednesday, June 17, 1998 6:44:40 o’clock AM GMT+00:00
*/
public class AnQ_13 {

	public static void main(String[] args) {
		System.out.print("Hell");
		System.out.println("o world");
	}

}
